var foodList = {
    side: [
    'Fresh green beans',
    'Fruit salad',
    'Garden salad',
    'Mashed potatoes',
    'Couscous',
    'Roasted zucchini',
    'Steamed broccoli with cheese',
    'Roasted Brussel sprouts',
    'Quinoa',
    'Sweet potatoes',
    'Coleslaw',
    'Cottage cheese',
    'Lo mein',
    'Butternut squash',
    'Creamed peas',
    'Cauliflower rice',
    'Bacon',
    'Stuffed peppers',
    'Mac n cheese',
    'Potato salad',   
    ],

    mainDish: [
    'Cheesy Turkey Broccoli Pasta',
    'Chicken or Beef Fajitas',
    'Chicken Paprikas',
    'Chicken Parmigiana',
    'Chicken Pot Pie',
    'Classic Baked Penne',
    'Classic Fettuccine Alfredo',
    'Company Lasagna',
    'Creamy Chicken Pasta',
    'Easy Bow Ties',
    'Delicious Farfalle',
    'Easy Chicken Casserole',
    'Easy Chicken Marinara',
    'Kielbasa Skillet',
    'Lasagne',
    'Mexican Skillet Dinner',
    'Northwest Style Linguine',
    'One Pot Spaghetti',
    'Oven BBQ Chicken Wings',
    ],

    dessert: [
    'Tiramisu',
    'Castella',
    'Chiffon cake',
    'Lady finger',
    'Apple pie',
    'Cup cake',
    'Chocolate',
    'Rum ball',
    'Marshmallow',
    'Salt water taffy',
    'Gingerbread cookie',
    'Oatmeal raisin cookie',
    'Butter pecan',
    'Creme brulee',
    'Pudding',
    'Fruit cup',
    'Ice cream',
    'Egg tart',
    'Timbits',
    'Iced coffee',
    'Bubble tea',
    ]
}
